// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import FavoriteProductsController from "./favorite_products_controller"
application.register("favorite-products", FavoriteProductsController)
